on:
  workflow_call:
    inputs:
      node-version:
        description: "A Node.js version spec to use and install. Examples: lts/*, 14.x, 16"
        type: string
        required: false
      node-version-file:
        description: "A path to file containing Node.js version spec. Examples: .node-version .nvmrc"
        type: string
        required: false
      runs-on:
        # https://github.com/orgs/community/discussions/26801
        description: 'Type of machine of job to run on. Needs to be quoted, because to support self-hosted labels and inputs does not support Array nor multiple types (default: "ubuntu-latest")'
        type: string
        default: '"ubuntu-latest"'
        required: false
      registry-url:
          description: "The registry URL to publish to. Examples: https://registry.npmjs.org/ https://npm.pkg.github.com/"
          type: string
          required: true
    secrets:
      NODE_AUTH_TOKEN:
        description: "The token to use for authentication with the registry."
        required: true

# outputs: - no output available

jobs:
  publish:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          registry-url: ${{ inputs.registry-url }}
          cache: 'npm'
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run compose script if exists
        run: npm run --if-present compose

      - name: Build TypeScript project
        run: npm run build

      - name: Publish/release package to npm and GitHub packages registry
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
