on:
  workflow_call:
    inputs:
      node-version:
        description: "A Node.js version spec to use and install. Examples: lts/*, 14.x, 16"
        type: string
        required: false
      node-version-file:
        description: "A path to file containing Node.js version spec. Examples: .node-version .nvmrc"
        type: string
        required: false
      registry-url:
        type: string
        default: "https://registry.npmjs.com"
        required: false
      runs-on:
        # https://github.com/orgs/community/discussions/26801
        description: 'Type of machine of job to run on. Needs to be quoted, because to support self-hosted labels and inputs does not support Array nor multiple types (default: "ubuntu-latest")'
        type: string
        default: '"ubuntu-latest"'
        required: false

# outputs: - no output available

jobs:
  lint:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: latest

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          registry-url: ${{ inputs.registry-url }}
          cache: 'pnpm'
          check-latest: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run compose script if exists
        run: pnpm run --if-present compose

      - name: Lint code
        run: pnpm run lint
