on:
  workflow_call:
    inputs:
      node-version:
        description: "A Node.js version spec to use and install. Examples: lts/*, 14.x, 16"
        type: string
        required: false
      node-version-file:
        description: "A path to file containing Node.js version spec. Examples: .node-version .nvmrc"
        type: string
        required: false
      registry-url:
        type: string
        default: "https://registry.npmjs.com"
        required: false
      runs-on:
        # https://github.com/orgs/community/discussions/26801
        description: 'Type of machine of job to run on. Needs to be quoted, because to support self-hosted labels and inputs does not support Array nor multiple types (default: "ubuntu-latest")'
        type: string
        default: '"ubuntu-latest"'
        required: false

# outputs: - no output available

jobs:
  publish:
    strategy:
      matrix:
        include:
          - registry-url: https://registry.npmjs.org/
            token_secret_key: NPM_TOKEN
          - registry-url: https://npm.pkg.github.com/
            token_secret_key: GITHUB_TOKEN

    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          registry-url: ${{ matrix.registry-url }}
          cache: 'pnpm'
          check-latest: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run compose script if exists
        run: pnpm run --if-present compose

      - name: Build TypeScript project
        run: pnpm run build

      - name: Publish/release package to npm and GitHub packages registry
        run: pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token_secret_key] }}
