on:
  workflow_call:
    inputs:
      node-version:
        description: "A Node.js version spec to use and install. Examples: lts/*, 14.x, 16"
        type: string
        required: false
      node-version-file:
        description: "A path to file containing Node.js version spec. Examples: .node-version .nvmrc"
        type: string
        required: false
      registry-url:
        type: string
        default: "https://registry.npmjs.com"
        required: false
      runs-on:
        # https://github.com/orgs/community/discussions/26801
        description: 'Type of machine of job to run on. Needs to be quoted, because to support self-hosted labels and inputs does not support Array nor multiple types (default: "ubuntu-latest")'
        type: string
        default: '"ubuntu-latest"'
        required: false

# outputs: - no output available

jobs:
  lint:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          registry-url: ${{ inputs.registry-url }}
          cache: 'pnpm'
          check-latest: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run compose script if exists
        run: pnpm run --if-present compose

      - name: Lint code
        run: pnpm run lint
